commandSequence = command+
command = decrementLoop / incrementCommand / decrementCommand

decrementLoop = "(" commands:commandSequence ")" reg:integer { return {action: "loopUntilZero", register: reg, commands: commands}; }
incrementCommand = [aA] reg:integer { return {action: "increment", register: reg }}
decrementCommand = [sS] reg:integer { return {action: "decrement", register: reg }}
integer = digits:[0-9]+ { return digits.join("") }
